#!/usr/bin/perl
use strict;
use warnings;

my $filename = shift;

my $md = `markdown $filename`;

$md =~ s{<h1>(.*?)</h1>}{};

my $title = $1;

my @slides = split(/^<hr \/>$/sm, $md);

my $html = <<HTML;
<!doctype html>
<html lang="en-us">
<head>
    <title>$title</title>
    <meta charset="utf-8"/>
    <!--
    <meta name="viewport" content="width=1274, user-scalable=no"/>
    -->
    <link rel="stylesheet" href="../ribbon/styles/screen.css"/>
    <style>
    .slide p {
        margin-bottom: 25px;
        display: inline;
    }
    .slide pre {
        margin-bottom: 25px;
    }
    .slide>div {
        padding-top: 60px;
    }
    .slide:after {
        display: none;
    }
    .slide pre code {
        -line-height: 1.7;
    }
    .slide pre code:before {
        content: '';
    }
    /*
    .slide section:before {
        display: none;
    }
    */
    </style>
</head>

<body class="list">
    <header class="caption">
        <h1>$title</h1>
    </header>

HTML

my $i = 0;
for my $slide (@slides) {
    $i++;
    $slide =~ s{(<h2>.*?</h2>)}{<header>$1</header>}gsm;
    $html .= <<HTML
    <div class="slide" id="slide-$i"><div><section>$slide</section></div></div>

HTML
}

$html .= <<HTML;

    <script src="../core/shower.js"></script>
</body>
</html>
HTML

print $html;

